# Print the equivalent curl commands for reference
print("\\n=== Equivalent curl Commands ===")
print()
print('# GET a user')
print('curl -s https://jsonplaceholder.typicode.com/users/1 | python -m json.tool')
print()
print('# POST a new post')
print('curl -X POST https://jsonplaceholder.typicode.com/posts \\\\')
print('  -H "Content-Type: application/json" \\\\')
print('  -d \'{"title": "My Test Post", "body": "Testing", "userId": 1}\'')
print()
print('# PATCH (update) a post')
print('curl -X PATCH https://jsonplaceholder.typicode.com/posts/1 \\\\')
print('  -H "Content-Type: application/json" \\\\')
print('  -d \'{"title": "Updated Title"}\'')
print()
print('# DELETE a post')
print('curl -X DELETE https://jsonplaceholder.typicode.com/posts/1')